In [274]:
# https://docs.google.com/presentation/d/15FfFp5yB291TDREl09nRohRYMqkYkcUN3UOHqIXeaKY/edit#slide=id.gcb9a0b074_1_0
# Land Belenky
#
# 2018.05.14

In [275]:
import numpy as np
import pandas as pd

In [276]:
'''
Scalar:   
A single number
May have any value (positive or negative)
Does not have a direction
'''

'\nScalar:   \nA single number\nMay have any value (positive or negative)\nDoes not have a direction\n'

In [277]:
'''
Vector:   
A group of numbers (scalars)
May be a row or a column
Order of the numbers is important as they correspond to different dimensions
'''

'\nVector:   \nA group of numbers (scalars)\nMay be a row or a column\nOrder of the numbers is important as they correspond to different dimensions\n'

In [278]:
'''
Matrix:

A 2-Dimensional collection of scalars
(e.g. a spreadsheet)
Position is important
By convention: rows x columns (m x n)
May be square or rectangular
May be tall or wide
May not be ragged (missing data filled with NaN)
'''

'\nMatrix:\n\nA 2-Dimensional collection of scalars\n(e.g. a spreadsheet)\nPosition is important\nBy convention: rows x columns (m x n)\nMay be square or rectangular\nMay be tall or wide\nMay not be ragged (missing data filled with NaN)\n'

In [279]:
'''
Example of a Ragged List:

Allowed in python, not numpy
'''
ragged_list = [[1,2,3],[1,2],[1,2,3,4],[1],[1,2,3,4,5]]
for i in ragged_list:
    print(i)

[1, 2, 3]
[1, 2]
[1, 2, 3, 4]
[1]
[1, 2, 3, 4, 5]


In [280]:
'''
numpy does not allow ragged lists
'''
#ragged_array = np.array([1,2,3],[1,2],[1,2,3,4],[1],[1,2,3,4,5])
#ragged_array


'\nnumpy does not allow ragged lists\n'

In [281]:
'''
you can make an array of lists
'''
ragged_array = np.array([[1,2,3],[1,2],[1,2,3,4],[1],[1,2,3,4,5]])
ragged_array

array([list([1, 2, 3]), list([1, 2]), list([1, 2, 3, 4]), list([1]),
       list([1, 2, 3, 4, 5])], dtype=object)

In [282]:
'''
A proper numpy array:
'''
proper_array = np.array([[1,2,3],[1,2,3],[1,2,3]])
proper_array

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [283]:
'''
Use np.NaN (Not a Number) to fill missing values:
'''
NaN_array = np.array([[1,2,3,np.NaN],[np.NaN,2,3,4],[1,np.NaN,3,4]])
NaN_array

array([[  1.,   2.,   3.,  nan],
       [ nan,   2.,   3.,   4.],
       [  1.,  nan,   3.,   4.]])

In [284]:
np.NaN is np.nan


True

In [285]:
'''
Tensor:

A collection of scalars with more than 2 Dimensions
(e.g. a workbook of spreadsheets)
Position is important
Rank: is the number of dimensions
Again: may not be ragged; missing data filled with NaN

Workbook = Tensor of Rank 3

Matrix = Tensor of Rank 2

Vector = Tensor of Rank 1

Scalar = Tensor of Rank 0


'''

'\nTensor:\n\nA collection of scalars with more than 2 Dimensions\n(e.g. a workbook of spreadsheets)\nPosition is important\nRank: is the number of dimensions\nAgain: may not be ragged; missing data filled with NaN\n\nWorkbook = Tensor of Rank 3\n\nMatrix = Tensor of Rank 2\n\nVector = Tensor of Rank 1\n\nScalar = Tensor of Rank 0\n\n\n'

In [286]:
# slide 20
x = np.array([
             [[ 0,1,2],
              [ 3,4,5]],
             [[ 9,10,11],
              [15,16,17]],
             [[2,10,8],
              [5,4,9]],
             [[18,19,20],
              [24,25,26]]
            ])
x.shape


(4, 2, 3)

In [287]:
'''
capital X denotes transposed matrix
'''
#import numpy as np
X = np.array([[1,2,3],[4,5,6],[7,8,9]])
X

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [288]:
#import numpy as np
X = np.array([[1,2,3],[4,5.0,6],[7,8,9]])
X

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.]])

In [289]:
#import numpy as np
X = np.array([[1,2,3],[4,'hello',6],[7,8,9]])
X

array([['1', '2', '3'],
       ['4', 'hello', '6'],
       ['7', '8', '9']],
      dtype='<U21')

In [290]:
B = np.array([[True,True],[False,False]])
B

array([[ True,  True],
       [False, False]], dtype=bool)

In [291]:
B = np.array([[True,0],[False,True]])
B

array([[1, 0],
       [0, 1]])

In [292]:
class animal():
    def __init__(self, genus, species):
        self.genus = genus
        self.species = species
    def __repr__(self):
        return self.genus + ' ' + self.species

In [293]:
monkey = animal('macaca','fuscata')
platypus = animal('ornithorhynchus','anatinus')
animals = np.array([monkey, platypus])
animals

array([macaca fuscata, ornithorhynchus anatinus], dtype=object)

In [294]:
type(animals[0])


__main__.animal

In [295]:
X = np.array([[1,2,3],[4,5,6],[7,8,9]])
X

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [296]:
X.ndim

2

In [297]:
X.shape

(3, 3)

In [298]:
X.size

9

In [299]:
np.array([1,2,3]).shape

(3,)

In [300]:
np.array([[1,2,3]]).shape

(1, 3)

In [301]:
np.array([[1],[2],[3]]).shape

(3, 1)

In [302]:
X

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [303]:
X.sum()

45

In [304]:
# axis = 0 means 'down each column, to create a row-shaped result'
X.sum(axis=0)

array([12, 15, 18])

In [305]:
# axis = 1 means 'across each row, to create a column-shaped result'
X.sum(axis=1)

array([ 6, 15, 24])

In [306]:
X

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [307]:
X.max( axis = 0)

array([7, 8, 9])

In [308]:
X.min( axis = 0)

array([1, 2, 3])

In [309]:
X.min()

1

In [310]:
X.max()

9

In [311]:
X.mean(axis = 0)

array([ 4.,  5.,  6.])

In [312]:
X.mean()

5.0

In [313]:
X.std(axis=0)

array([ 2.44948974,  2.44948974,  2.44948974])

In [314]:
'''
np.arange(start, stop, step_size)

Note: “start” is included but “stop” is not

Defaults to start = 0, step = 1 

'''
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [315]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [316]:
np.arange(5,10, 0.5)

array([ 5. ,  5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5])

In [317]:
X = np.arange(12)
X
X.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [318]:
X.reshape(6,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [319]:
X.reshape(4,-1)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [320]:
X.reshape(-1,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [321]:
#X.reshape(5,-1)
#X.reshape(-1,-1)

In [322]:
X = np.arange(24).reshape(2,3,-1)
X

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [323]:
X.reshape(6,-1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [324]:
X.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [325]:
X.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [326]:
'''
np.linspace(start, stop, number_of_elements)

Similar to arange, but inclusive on both ends and number_of_elements rather than step_size:

'''
np.linspace(0,10,11)

array([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.])

In [327]:
np.arange(0,11,1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [328]:
np.logspace(0,3,4)

array([    1.,    10.,   100.,  1000.])

In [329]:
np.zeros((8,8))

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [330]:
np.ones((6,6))

array([[ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.]])

In [331]:
'''
How would you make the equivalent of an np.sixes() method?

'''
rows = columns = 5
np.ones((rows, columns))*6

array([[ 6.,  6.,  6.,  6.,  6.],
       [ 6.,  6.,  6.,  6.,  6.],
       [ 6.,  6.,  6.,  6.,  6.],
       [ 6.,  6.,  6.,  6.,  6.],
       [ 6.,  6.,  6.,  6.,  6.]])

In [332]:
np.zeros((rows,columns))+6

array([[ 6.,  6.,  6.,  6.,  6.],
       [ 6.,  6.,  6.,  6.,  6.],
       [ 6.,  6.,  6.,  6.,  6.],
       [ 6.,  6.,  6.,  6.,  6.],
       [ 6.,  6.,  6.,  6.,  6.]])

In [333]:
X = np.random.randint(1,10,20)
X

array([2, 3, 6, 2, 5, 8, 3, 8, 8, 4, 6, 5, 5, 7, 7, 8, 9, 7, 9, 9])

In [334]:
X.tofile('data.csv')
A = np.fromfile('data.csv', dtype = 'int64')
A

array([2, 3, 6, 2, 5, 8, 3, 8, 8, 4, 6, 5, 5, 7, 7, 8, 9, 7, 9, 9])

In [335]:
np.array_equal(A,X)

True

In [336]:
from sklearn.datasets import load_iris

In [337]:
iris_data = load_iris()
data = iris_data['data']

In [338]:
import pandas as pd
df = pd.DataFrame(data)
df.head(2)

0    1    2    3
0  5.1  3.5  1.4  0.2
1  4.9  3.0  1.4  0.2

In [339]:
data2 = df.values

In [340]:
np.array_equal(data, data2)

True

In [341]:
type(data) == type(data2)

True

In [342]:
A = np.arange(1,101,1).reshape(10,10)
A

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [343]:
a = np.arange(1,101).reshape(10,-1)
# Rank
a.ndim


2

In [344]:
a.size

100

In [345]:
a.shape

(10, 10)

In [346]:
# row mean
a.mean(axis = 1)

array([  5.5,  15.5,  25.5,  35.5,  45.5,  55.5,  65.5,  75.5,  85.5,  95.5])

In [347]:
# col mean
a.mean(axis =0)

array([ 46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.])

In [348]:
# create a vector that has 50 points and spans the range 11 to 23
b = np.random.randint(11,23,50)
b

array([21, 14, 12, 15, 20, 22, 14, 19, 19, 21, 16, 16, 18, 12, 22, 13, 19,
       15, 12, 15, 18, 17, 13, 16, 11, 19, 21, 12, 15, 12, 20, 21, 17, 17,
       15, 18, 18, 20, 14, 13, 19, 21, 16, 15, 16, 15, 22, 21, 22, 16])

In [349]:
# OR
# create a vector that has 50 points and spans the range 11 to 23
b = np.linspace(11,23,50)
b

array([ 11.        ,  11.24489796,  11.48979592,  11.73469388,
        11.97959184,  12.2244898 ,  12.46938776,  12.71428571,
        12.95918367,  13.20408163,  13.44897959,  13.69387755,
        13.93877551,  14.18367347,  14.42857143,  14.67346939,
        14.91836735,  15.16326531,  15.40816327,  15.65306122,
        15.89795918,  16.14285714,  16.3877551 ,  16.63265306,
        16.87755102,  17.12244898,  17.36734694,  17.6122449 ,
        17.85714286,  18.10204082,  18.34693878,  18.59183673,
        18.83673469,  19.08163265,  19.32653061,  19.57142857,
        19.81632653,  20.06122449,  20.30612245,  20.55102041,
        20.79591837,  21.04081633,  21.28571429,  21.53061224,
        21.7755102 ,  22.02040816,  22.26530612,  22.51020408,
        22.75510204,  23.        ])

In [350]:
###  Matris ops

'''
A brief aside about Transpose:

Transpose changes a column vector into a row vector or vice versa.

For a matrix, it swaps row and columns (changing from tall to wide or vice versa)

'''
x = np.array([[3,4,5,6]]).T
y = np.array([[3],[4],[5],[6]])

In [351]:
x

array([[3],
       [4],
       [5],
       [6]])

In [352]:
y

array([[3],
       [4],
       [5],
       [6]])

In [353]:
np.array_equal(x,y)

True

In [354]:
X = np.arange(24).reshape(6,-1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [355]:
X.T

array([[ 0,  4,  8, 12, 16, 20],
       [ 1,  5,  9, 13, 17, 21],
       [ 2,  6, 10, 14, 18, 22],
       [ 3,  7, 11, 15, 19, 23]])

In [356]:
import math
n = math.factorial(7)
n

5040

In [357]:
N = np.arange(n).reshape(2,3,4,5,6,7)
N.shape

(2, 3, 4, 5, 6, 7)

In [358]:
N.T.shape

(7, 6, 5, 4, 3, 2)

In [359]:
'''
A Machine Learning Example:  

Supervised Learning -- predicting an output from a set of inputs

Suppose we have a set of input variables (X) that describe Colorado and we want to predict snowfall from these.

X is composed of a set of vectors (x) which each describe one feature (elevation, latitude, average winter temperature, historical snowfall data, etc…)

We want to predict y, which is the expected snowfall for each point in our dataset.


'''

'\nA Machine Learning Example:  \n\nSupervised Learning -- predicting an output from a set of inputs\n\nSuppose we have a set of input variables (X) that describe Colorado and we want to predict snowfall from these.\n\nX is composed of a set of vectors (x) which each describe one feature (elevation, latitude, average winter temperature, historical snowfall data, etc…)\n\nWe want to predict y, which is the expected snowfall for each point in our dataset.\n\n\n'

In [360]:
# if we think of the features of a matrix as column vectors
feature1 = np.array([[99,45,31,14]]).T
feature2 = np.array([[0,1,1,1]]).T
feature3 = np.array([[5,3,9,24]]).T


In [361]:
# we can stack them into a matrix using hstack
X = np.hstack([feature1, feature2, feature3])
X

array([[99,  0,  5],
       [45,  1,  3],
       [31,  1,  9],
       [14,  1, 24]])

In [362]:
# vstack
row1 =np.array([['r','o','w','1']])
row2 =np.array([['r','o','w','2']])
M1 = np.vstack([row1,row2])
M1


array([['r', 'o', 'w', '1'],
       ['r', 'o', 'w', '2']],
      dtype='<U1')

In [363]:
col1 = np.array([['c','o','l','u','m','n','1']]).T
col2 = np.array([['c','o','l','u','m','n','2']]).T
M2 = np.hstack([col1,col2])
M2


array([['c', 'c'],
       ['o', 'o'],
       ['l', 'l'],
       ['u', 'u'],
       ['m', 'm'],
       ['n', 'n'],
       ['1', '2']],
      dtype='<U1')

In [364]:
M3 = np.hstack([row1,row2])
M3

array([['r', 'o', 'w', '1', 'r', 'o', 'w', '2']],
      dtype='<U1')

In [365]:
M4 = np.vstack([col1,col2])
M4

array([['c'],
       ['o'],
       ['l'],
       ['u'],
       ['m'],
       ['n'],
       ['1'],
       ['c'],
       ['o'],
       ['l'],
       ['u'],
       ['m'],
       ['n'],
       ['2']],
      dtype='<U1')

In [366]:
# dimension mismatch
#M5 = np.hstack([row1,col2])

In [367]:
X = np.hstack([feature1, feature2, feature3])
X

array([[99,  0,  5],
       [45,  1,  3],
       [31,  1,  9],
       [14,  1, 24]])

In [368]:
X[0,2]

5

In [369]:
X[1,0]

45

In [370]:
X[1]

array([45,  1,  3])

In [371]:
X[:,1]

array([0, 1, 1, 1])

In [372]:
X[1::2,0:-1:1]

array([[45,  1],
       [14,  1]])

In [373]:
# Note the difference between Python and Numpy indexing:
python_array = [[1,2,3],[4,5,6],[7,8,9]]
python_array

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [374]:
numpy_array = np.array(python_array)
numpy_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [375]:
numpy_array[1,1]

5

In [376]:
python_array[1][1]

5

In [377]:
# Indexing Works for setting values also
X = np.arange(100).reshape(10,-1)
X[5] = np.zeros(10)
X[:,5] = np.ones(10)
X

array([[ 0,  1,  2,  3,  4,  1,  6,  7,  8,  9],
       [10, 11, 12, 13, 14,  1, 16, 17, 18, 19],
       [20, 21, 22, 23, 24,  1, 26, 27, 28, 29],
       [30, 31, 32, 33, 34,  1, 36, 37, 38, 39],
       [40, 41, 42, 43, 44,  1, 46, 47, 48, 49],
       [ 0,  0,  0,  0,  0,  1,  0,  0,  0,  0],
       [60, 61, 62, 63, 64,  1, 66, 67, 68, 69],
       [70, 71, 72, 73, 74,  1, 76, 77, 78, 79],
       [80, 81, 82, 83, 84,  1, 86, 87, 88, 89],
       [90, 91, 92, 93, 94,  1, 96, 97, 98, 99]])

In [378]:
'''
The Dot Product

in order to multiply two matrices, they must be conformable such that the number of columns 
in matrix 1, is the same as the number or columns in matrix 2
A(n by m) * B(m by p) = X(n by p)
NOTE:
This means that Dot Product is not commutative. 
If A.dot(B) exists, it does not imply that B.dot(A) also exists.  
Even if B.dot(A) does it exist, in general, it will have different shape and/or different values than A.dot(B) 

'''

'\nThe Dot Product\n\nin order to multiply two matrices, they must be conformable such that the number of columns \nin matrix 1, is the same as the number or columns in matrix 2\nA(n by m) * B(m by p) = X(n by p)\nNOTE:\nThis means that Dot Product is not commutative. \nIf A.dot(B) exists, it does not imply that B.dot(A) also exists.  \nEven if B.dot(A) does it exist, in general, it will have different shape and/or different values than A.dot(B) \n\n'

In [379]:
'''
When we say multiply two matrices it does not mean multiply in the sense that you might think. The matrix product of two matrices is another matrix.

If we have two vectors x and y of the same length (n), then the dot product is give by

x⋅y=x1y1+x2y2+⋯+xnyn
'''

'\nWhen we say multiply two matrices it does not mean multiply in the sense that you might think. The matrix product of two matrices is another matrix.\n\nIf we have two vectors x and y of the same length (n), then the dot product is give by\n\nx⋅y=x1y1+x2y2+⋯+xnyn\n'

In [380]:
# math operators work elementwise
a = np.array([3,4,5])
b = np.ones(3)
a - b

array([ 2.,  3.,  4.])

In [381]:
# Something that can be tricky for people familar with other programming languages is that 
# the * operator does not carry out a matrix product. This is done with the dot function.

a = np.array([[1,2],[3,4]])
b = np.array([[1,2],[3,4]])
print(a)
#array([[1, 2],
#       [3, 4]])
print(b)
#array([[1, 2],
#       [3, 4]])
print(a * b)
#array([[ 1,  4],
#       [ 9, 16]])
print (np.dot(a,b))

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]
[[ 1  4]
 [ 9 16]]
[[ 7 10]
 [15 22]]


In [382]:
np.dot(np.array([[1,2,3]]),np.array([[2,3,4]]).T)
#  1*2  + 2*3  + 3*4 = 20

array([[20]])

In [383]:
np.dot(np.array([1,2,3,4]), np.array([3,4,5,6]))

50

In [384]:
np.dot(np.array([[1,2,3]]),np.array([[2,3,4]]).T)

array([[20]])

In [385]:
a = [1,2,3]
b = [4,5,6]
a+b

[1, 2, 3, 4, 5, 6]

In [386]:
A = np.array(a)
B = np.array(b)
A+B

array([5, 7, 9])

In [387]:
a

[1, 2, 3]

In [388]:
a2 = a*2
a2

[1, 2, 3, 1, 2, 3]

In [389]:
A2 = A*2
A2

array([2, 4, 6])

In [390]:
a = np.zeros((2,2),dtype='float')
a += 5
a

array([[ 5.,  5.],
       [ 5.,  5.]])

In [391]:
a *= 5
a

array([[ 25.,  25.],
       [ 25.,  25.]])

In [392]:
'''
Vectorized Calculations
Suppose we have associated arrays of heights and weights and we want to calculate BMI.

We could use a for loop:

'''
heights = np.array([1.8,1.6,1.7,1.5,1.9,2.0])
weights = np.array([55, 60, 75, 80, 70, 65])
BMI = np.zeros(heights.shape)
for i,(w,h) in enumerate(zip(weights, heights)):
    BMI[i] = w/(h**2)
BMI

array([ 16.97530864,  23.4375    ,  25.95155709,  35.55555556,
        19.39058172,  16.25      ])

In [393]:
# We could use a list comprehension:
BMI = np.array(list([w/(h**2)] for w,h in zip(weights, heights)))
BMI


array([[ 16.97530864],
       [ 23.4375    ],
       [ 25.95155709],
       [ 35.55555556],
       [ 19.39058172],
       [ 16.25      ]])

In [394]:
# But the numpy was is to do it with one command, operating on the whole array in one shot:
BMI = weights/heights**2
BMI

array([ 16.97530864,  23.4375    ,  25.95155709,  35.55555556,
        19.39058172,  16.25      ])

In [395]:
# random arrays
x = np.random.randint(0,10,5)
x.sort()
x

array([0, 6, 6, 6, 7])

In [396]:
x = np.random.random(10)
x

array([ 0.86231289,  0.04058392,  0.40547258,  0.0567768 ,  0.22255879,
        0.46253931,  0.13896271,  0.31884441,  0.86211569,  0.50058529])

In [397]:
X = np.random.random(size = (4,4))
X

array([[ 0.25745583,  0.06444258,  0.50619897,  0.23690261],
       [ 0.45418517,  0.8257832 ,  0.38089239,  0.71673636],
       [ 0.64820276,  0.25538793,  0.24592458,  0.42455784],
       [ 0.97459399,  0.81060614,  0.23288491,  0.3373661 ]])

In [398]:
x = np.random.randint(0,10,5)
#x = np.random.shuffle(x)[:3]
x

array([5, 6, 8, 3, 3])

In [399]:
np.random.choice(x,3)

array([6, 8, 5])

In [400]:
# find teh 3 highest scores
bowlers = np.array(['Al','Bob','Charlie','Dan','Ezra','Frank'])
scores  = np.array([220,260,195,280,210,240])
scores.sort()
scores[-3:]

array([240, 260, 280])

In [401]:
# but the bowlers are not aligned
bowlers[-3:]

array(['Dan', 'Ezra', 'Frank'],
      dtype='<U7')

In [402]:
# the best half of golfers advances
golfers = np.array(['Amy','Betty','Cindy','Dawn','Emily','Fran','Georgina','Heather'])
scores  = np.random.randint(65,95, golfers.size)
scores

array([77, 90, 74, 69, 71, 66, 81, 68])

In [403]:
leaders = golfers[scores.argsort()][:int(golfers.size/2)]
leaders

array(['Fran', 'Heather', 'Dawn', 'Emily'],
      dtype='<U8')

In [404]:
# find the 3 best
bowlers = np.array(['Al','Bob','Charlie','Dan','Ezra','Frank'])
scores  = np.array([220,260,195,280,210,240])
best_to_worst = scores.argsort()[::-1]
best_to_worst

array([3, 1, 5, 0, 4, 2])

In [405]:
bowlers[best_to_worst][:3]

array(['Dan', 'Bob', 'Frank'],
      dtype='<U7')

In [406]:
# some other fct's
x = np.arange(1,5)
np.sqrt(x)

array([ 1.        ,  1.41421356,  1.73205081,  2.        ])

In [407]:
np.power(x,2)

array([ 1,  4,  9, 16])

In [408]:
np.log(x)

array([ 0.        ,  0.69314718,  1.09861229,  1.38629436])

In [417]:
geneList = np.array(["A2M", "FOS", "BRCA2","CPOX"])
values0  = np.array([0.12,0.08,0.06,0.02])
values1  = np.array([0.01,0.07,0.11,0.09])
values2  = np.array([0.03,0.04,0.04,0.02])
values3  = np.array([0.05,0.09,0.11,0.14])
X = np.array([values0, values1, values2, values3  ]) #, values2, values3)
X

array([[ 0.12,  0.08,  0.06,  0.02],
       [ 0.01,  0.07,  0.11,  0.09],
       [ 0.03,  0.04,  0.04,  0.02],
       [ 0.05,  0.09,  0.11,  0.14]])

In [414]:
mean_gene = X.mean(axis=1)
mean_gene

array([ 0.07  ,  0.07  ,  0.0325,  0.065 ])

In [415]:
mean_time = X.mean(axis=0)
mean_time

array([ 0.0525,  0.07  ,  0.08  ,  0.035 ])

In [416]:
geneList[(mean_gene.argmax())]

'A2M'

In [ ]:
'''
the transpose of an n by m matrix is an m by n matrix with rows and cls interchanged.
A transpose can be thought of as the mirror image if a matrix across the main diagonal
'''

In [ ]:
'''
Let X be an (n by m0 matrix and a real mumber.
then  (cX)^^T = cX^^T
)'''

In [ ]:
'''
Let X and Y be (n by p) matrices, then
(X +- Y)^^T = X^^T +- Y^^T
'''

In [ ]:
'''
Let X be an (n by k) matrix and Y be an (k by p) matrix, then
(XY)^^T = Y^^T * X^^T
'''

In [418]:
'''
if we have 2 vectors of the same length "n",
then the dor product is given by
x * y = x1y1 + x2y2 + ...xnyn
'''
x = np.array([1,2,3,4])
y = np.array([4,3,2,1])
np.dot(x,y)

20

In [419]:
# physical interpretation
# if x*y = 0, they are orthogonal

w = np.array([1,2])
v = np.array([-2,1])
np.dot(w,v)

0

In [420]:
'''
the dot product is the same as the INNER product : (1 by n) vector * (n by 1) vector:
x^^T * y
an OUTER product is the opposite;
xy^^T
'''
# Inner
a = np.array([[1,2,3]])
b = np.array([[4,5,6]])
a.dot(b.T)

array([[32]])

In [421]:
# outer
a.T.dot(b)

array([[ 4,  5,  6],
       [ 8, 10, 12],
       [12, 15, 18]])

In [422]:
a = a.flatten()
b = b.flatten()
a.dot(b)

32

In [423]:
b.dot(a)

32

In [424]:
a.T.dot(b)

32

In [426]:
a.dot(b.T)

32

In [427]:
'''
 matrix determinant - square matrix ONLY
 the determinant of a 2-d array is a*d - b*c
      a   b
 x =  c   d
 
'''
a=np.array([[1,2],[3,4]])
np.linalg.det(a)


-2.0000000000000004

In [428]:
# identoty matrix
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [ ]:
'''
division is not defined for matrix operations.
SO to find X in:
A = B * X

B^^(-1) * A = B^^(-1) * B * x
# multiply by B^^(-1) is positional - to the left on BOTH sides
B^^(-1) * A = I * X # identity matrix substitution
B^^(-1) * A = X
'''

In [429]:
A = np.array([[-4,-2],[5,5]])
A

array([[-4, -2],
       [ 5,  5]])

In [430]:
invA = np.linalg.inv(A)
invA

array([[-0.5, -0.2],
       [ 0.5,  0.4]])

In [432]:
np.round(np.dot(A,invA))
# because A*A^^(-1) = A^^(-1)*A = I

array([[ 1.,  0.],
       [ 0.,  1.]])